global:
  imagePullPolicy: IfNotPresent

movie:
  image:
    repository: united74/movie-service
    tag: latest
  port: 8000
  # nodePort: 30003

cast:
  image:
    repository: united74/cast-service
    tag: latest
  port: 8001

postgres:
  image: postgres:12.1-alpine
  port: 5432
  env:
    POSTGRES_USER: username
    POSTGRES_PASSWORD: password
    POSTGRES_DB: db

nginx:
  image: nginx:alpine
  port: 80

ingress:
  className: traefik
  host: staging.albay.ip-ddns.com

persistence:
  size: 5Gi
  storageClass: local-path

