global:
  imagePullPolicy: IfNotPresent

movie:
  image:
    repository: united74/movie-service
    tag: latest
  port: 8000
  # nodePort: 30002

cast:
  image:
    repository: united74/cast-service
    tag: latest
  port: 8001

postgres:
  image: postgres:12.1-alpine
  port: 5432
  env:
    POSTGRES_USER: username
    POSTGRES_PASSWORD: password
    POSTGRES_DB: db

nginx:
  image: nginx:1.29.6-alpine
  port: 80
  # nodePort: 30002

ingress:
  enabled: true
  className: traefik
  host: qa.albay.ip-ddns.com

persistence:
  size: 5Gi
  storageClass: local-path

certmanager:
  clusterIssuer: letsencrypt-qa

  