apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certmanager.clusterIssuer }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benkj31@gmail.com
    privateKeySecretRef:
      name: {{ .Values.certmanager.clusterIssuer }}
    solvers:
    - http01:
        ingress:
          class: traefik