apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name {{ .Values.ingress.host }};

      location /api/v1/movies {
        proxy_pass http://movie-service:8000; # Nom du Service K8s pour les films
      }

      location /api/v1/casts {
        proxy_pass http://cast-service:8000;  # Nom du Service K8s pour les casts
      }
    }