apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cast-{{ .Release.Namespace }}
  labels:
    app:  cast-service
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}


