apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pvc # pvc-cast-{{ .Release.Namespace }} # {{ .Release.Name }}-pvc // {{ .Release.Name }}-{{ .Chart.Name }}-pvc
  labels:
    app:  cast-service
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}


