apiVersion: v1
kind: Service
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  type: ClusterIP
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.cast.port }}
